### ISSUE TITLE
wrong ckpt in app.py

### ISSUE THREAD

**Issue by whmc76** [OpenGVLab/Diffree#1]
now it is diffree-step=000010999, but 
Loading model from checkpoints/epoch=000041-step=000010999.ckpt
Traceback (most recent call last):
  File "app.py", line 151, in <module>
    model = load_model_from_config(config, args.ckpt, args.vae_ckpt)
  File "app.py", line 47, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "C:\Users\28687\.conda\envs\diffree\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\28687\.conda\envs\diffree\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\28687\.conda\envs\diffree\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/epoch=000041-step=000010999.ckpt'

**Comment by Lirui-Zhao** [comment]
Hi,
These two checkpoints are consistent, thank you for helping us find a bug, we have modified the app.py file to keep the default file name as diffree-step=000010999.ckpt. Please ensure that you update the app.py file accordingly.

**Comment by whmc76** [comment]
哈哈我想应该是的 大概是重命名的 辛苦啦
